import{S as y,i}from"./assets/vendor-BrddEoy-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const s of e.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function a(r){if(r.ep)return;r.ep=!0;const e=n(r);fetch(r.href,e)}})();async function h(o,t=1,n=40){const a="48567917-ad299c95fd5743fafa8b1579d",r="https://pixabay.com/api/",e=new URLSearchParams({key:a,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n});try{const s=await fetch(`${r}?${e}`);if(!s.ok)throw new Error("Failed to fetch images");return await s.json()}catch(s){throw console.error("Error fetching images:",s),s}}function m(o,t=!1){const n=document.querySelector("#gallery"),a=o.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item" data-lightbox="gallery">
          <img src="${e.webformatURL}" alt="${e.tags}" />
          <div class="info">
            <p> likes </br> ${e.likes}</p>
            <p> views </br> ${e.views}</p>
            <p> comments </br> ${e.comments}</p>
            <p> downloads </br> ${e.downloads}</p>
          </div>
        </a>
      `).join("");t?n.insertAdjacentHTML("beforeend",a):n.innerHTML=a,new y(".gallery-item").refresh()}const p=document.querySelector("#search-form"),b=document.querySelector("#gallery"),f=document.querySelector("#loader"),c=document.querySelector("#load-more");let d="",l=1;const u=40,g=new y(".gallery a");c.style.display="none";p.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements.searchQuery.value.trim(),!d){i.error({message:"Please enter a search query!"});return}l=1,b.innerHTML="",c.style.display="none",f.classList.remove("hidden");try{const t=await h(d,l,u);t.hits.length===0?i.warning({message:"Sorry, no images found. Try again!"}):(m(t.hits),g.refresh(),t.totalHits>u&&(c.style.display="block"))}catch{i.error({message:"Error fetching images. Please try again later."})}finally{f.classList.add("hidden")}});c.addEventListener("click",async()=>{l+=1,f.classList.remove("hidden");try{const o=await h(d,l,u);m(o.hits,!0),g.refresh(),w();const t=Math.ceil(o.totalHits/u);l>=t&&(c.style.display="none",i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"Error fetching images. Please try again later."})}finally{f.classList.add("hidden")}});function w(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
