import{a as p,S as y,i}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function m(t,r=1,n=40){const s="48567917-ad299c95fd5743fafa8b1579d",e="https://pixabay.com/api/",o={key:s,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n};try{return(await p.get(e,{params:o})).data}catch(a){throw console.error("Error fetching images:",a),a}}const b=new y(".gallery-item");b.refresh();function g(t,r=!1){const n=document.querySelector("#gallery"),s=t.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item" data-lightbox="gallery">
          <img src="${e.webformatURL}" alt="${e.tags}" />
          <div class="info">
            <p> likes </br> ${e.likes}</p>
            <p> views </br> ${e.views}</p>
            <p> comments </br> ${e.comments}</p>
            <p> downloads </br> ${e.downloads}</p>
          </div>
        </a>
      `).join("");r?n.insertAdjacentHTML("beforeend",s):n.innerHTML=s}const L=document.querySelector("#search-form"),w=document.querySelector("#gallery"),f=document.querySelector("#loader"),c=document.querySelector("#load-more");let d="",l=1;const u=40,h=new y(".gallery a");c.style.display="none";L.addEventListener("submit",async t=>{if(t.preventDefault(),d=t.target.elements.searchQuery.value.trim(),!d){i.error({message:"Please enter a search query!"});return}l=1,w.innerHTML="",c.style.display="none",f.classList.remove("hidden");try{const r=await m(d,l,u);r.hits.length===0?i.warning({message:"Sorry, no images found. Try again!"}):(g(r.hits),h.refresh(),r.totalHits>u&&(c.style.display="block"))}catch{i.error({message:"Error fetching images. Please try again later."})}finally{f.classList.add("hidden")}});c.addEventListener("click",async()=>{l+=1,f.classList.remove("hidden");try{const t=await m(d,l,u);g(t.hits,!0),h.refresh(),v();const r=Math.ceil(t.totalHits/u);l>=r&&(c.style.display="none",i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"Error fetching images. Please try again later."})}finally{f.classList.add("hidden")}});function v(){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
